# Protection configuration section
  protection:
    # Name of the world where protection applies
    world: world
    center:
      # X coordinate of the protection center (decimal for precision)
      x: 0.5
      # Y coordinate (height) of the protection center
      y: 64.0
      # Z coordinate of the protection center (decimal for precision)
      z: 0.5
    # Protection radius in blocks
    radius: 64