name: BetterSpawnProtect
version: '1.0.0'
main: net.honeyberries.betterSpawnProtect.BetterSpawnProtect
api-version: '1.21'
authors: [ HoneyBerries ]
description: Spawn Protection Fix for Minecraft
website: honeyberries.net
folia-supported: true
permissions:
  betterspawnprotect.admin:
    description: Allows using BetterSpawnProtect admin commands
    default: op
  betterspawnprotect.bypass:
    description: Allows modifying blocks inside spawn protection
    default: op